[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#676767"
blue = "#6871ff"
cyan = "#5ffdff"
green = "#5ff967"
magenta = "#ff76ff"
red = "#ff6d67"
white = "#fffefe"
yellow = "#fefb67"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.line_indicator]
background = "None"
foreground = "#141414"

[colors.normal]
black = "#000000"
blue = "#0225c7"
cyan = "#00c5c7"
green = "#00c200"
magenta = "#c930c7"
red = "#c91b00"
white = "#c7c7c7"
yellow = "#c7c400"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
style = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[keyboard]
bindings = [
  { key = "c", mods = "Command", action = "Copy" },
  { key = "v", mods = "Command", action = "Paste" },
  { key = "T", mods = "Command", action = "CreateNewWindow" },
  # vim binding

  { key = "h", mods = "None", mode = "Vi", action = "Left" },
  { key = "j", mods = "None", mode = "Vi", action = "Down" },
  { key = "k", mods = "None", mode = "Vi", action = "Up" },
  { key = "l", mods = "None", mode = "Vi", action = "Right" },
  { key = "w", mods = "None", mode = "Vi", action = "WordRight" },
  { key = "b", mods = "None", mode = "Vi", action = "WordLeft" },

  # Selection and copying
  { key = "v", mods = "None", mode = "Vi", action = "ToggleNormalSelection" },   # Start selection
  { key = "y", mods = "None", mode = "Vi", action = "Copy" },                    # Copy selection to clipboard
  { key = "V", mods = "Shift", mode = "Vi", action = "ToggleLineSelection" },    # Line selection
  { key = "v", mods = "Control", mode = "Vi", action = "ToggleBlockSelection" }, # Block selection
  { key = "v", mods = "Alt", mode = "Vi", action = "ToggleSemanticSelection" },  # Semantic selection

  # Search
  { key = "/", mods = "None", mode = "Vi", action = "SearchForward" },   # Search forward
  { key = "?", mods = "None", mode = "Vi", action = "SearchBackward" },  # Search backward
  { key = "n", mods = "None", mode = "Vi", action = "SearchNext" },      # Next search result
  { key = "N", mods = "Shift", mode = "Vi", action = "SearchPrevious" }, # Previous search result

  # Exit vi mode
  { key = "Escape", mods = "None", mode = "Vi", action = "ClearSelection" }, # Clear selection and exit
  { key = "Space", mods = "Control", mode = "Vi", action = "ToggleViMode" },
]

[mouse]
hide_when_typing = false

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "full"
# None follows system
decorations_theme_variant = "None"
dynamic_title = true
startup_mode = "Maximized"
padding = { x = 10, y = 10 }

[general]
live_config_reload = true
