require("andrascsanyi.options")
require("andrascsanyi.keymaps")
require("andrascsanyi.lazy")
require("onedark").load()
-- require("andrascsanyi.nvim-tree")
-- require("andrascsanyi.colorscheme")
-- require("andrascsanyi.cmp")
-- require("andrascsanyi.lsp")
-- require("andrascsanyi.autopairs")
-- require("andrascsanyi.telescope")
-- require("andrascsanyi.treesitter")
-- require("andrascsanyi.comment")
-- require("andrascsanyi.gitsigns")
-- require("andrascsanyi.bufferline")
-- require("andrascsanyi.toggleterm")
-- require("andrascsanyi.cd-project")
-- require("andrascsanyi.indent-blankline")
-- require("andrascsanyi.alpha")
-- require("andrascsanyi.roslyn")
-- -- require "andrascsanyi.which-key"
-- require("andrascsanyi.lualine")
